[package]
name = "port_scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive", "wrap_help"] }
tokio = { version = "1.45.0", features = ["rt-multi-thread", "full"] }
